version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
  ports:
    - "8000:8000"
  volumes:
    - .:/ibarber
  command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

# depends_on:
#   - db

# db:
#   image: postgres:13
#   environment:
#     POSTGRES_DB: ibarber-db
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: docker