version: "4"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/ibarber
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: ibarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1501
    # ports:
    #   - "5432:5432"
